server:
  port: 9999

spring:
  datasource:
    url: jdbc:h2:~/playground-microservices-service-directory
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
logging:
  level:
    net.pkhapps.playground.microservices: debug

