server:
  port: 8880
  servlet:
    session:
      cookie:
        name: UISESSION

security:
  oauth2:
    client:
      access-token-uri: http://localhost:9990/oauth/token
      client-id: PortalServer
      client-secret: this-is-the-portal-server-secret
      user-authorization-uri: http://localhost:9990/oauth/authorize
      use-current-uri: true
      scope:
        profile
        email
    resource:
      user-info-uri: http://localhost:9990/user/me
      jwt:
        key-alias: authserver
        key-store: file:/Users/petterwork/playground-microservices.keystore
        key-store-password: notasecret
        key-password: notasecret

logging:
  level:
    org.springframework.security: info
