server:
  port: 9990
  servlet:
    session:
      cookie:
        name: AUTHUISESSION

security:
  oauth2:
    authorization:
      jwt:
        key-alias: authserver
        key-store: file:/Users/petterwork/playground-microservices.keystore
        key-store-password: notasecret
        key-password: notasecret

spring:
  datasource:
    url: jdbc:h2:/Users/petterwork/playground-microservices-auth-server
    driver-class-name: org.h2.Driver
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.springframework.security: info
